package com.hpetshop.pojo;

import java.util.Date;

public class HpUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hp_user.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hp_user.username
	 * @mbggenerated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hp_user.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hp_user.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hp_user.email
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hp_user.created
	 * @mbggenerated
	 */
	private Date created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column hp_user.updated
	 * @mbggenerated
	 */
	private Date updated;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hp_user.id
	 * @return  the value of hp_user.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hp_user.id
	 * @param id  the value for hp_user.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hp_user.username
	 * @return  the value of hp_user.username
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hp_user.username
	 * @param username  the value for hp_user.username
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hp_user.password
	 * @return  the value of hp_user.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hp_user.password
	 * @param password  the value for hp_user.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hp_user.phone
	 * @return  the value of hp_user.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hp_user.phone
	 * @param phone  the value for hp_user.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hp_user.email
	 * @return  the value of hp_user.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hp_user.email
	 * @param email  the value for hp_user.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hp_user.created
	 * @return  the value of hp_user.created
	 * @mbggenerated
	 */
	public Date getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hp_user.created
	 * @param created  the value for hp_user.created
	 * @mbggenerated
	 */
	public void setCreated(Date created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column hp_user.updated
	 * @return  the value of hp_user.updated
	 * @mbggenerated
	 */
	public Date getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column hp_user.updated
	 * @param updated  the value for hp_user.updated
	 * @mbggenerated
	 */
	public void setUpdated(Date updated) {
		this.updated = updated;
	}
}