package com.hpetshop.mapper;

import com.hpetshop.pojo.HpContentCategory;
import com.hpetshop.pojo.HpContentCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpContentCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	int countByExample(HpContentCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	int deleteByExample(HpContentCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	int insert(HpContentCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	int insertSelective(HpContentCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	List<HpContentCategory> selectByExample(HpContentCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	HpContentCategory selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpContentCategory record, @Param("example") HpContentCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpContentCategory record, @Param("example") HpContentCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpContentCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content_category
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpContentCategory record);
}