package com.hpetshop.mapper;

import com.hpetshop.pojo.HpContent;
import com.hpetshop.pojo.HpContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpContentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int countByExample(HpContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int deleteByExample(HpContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int insert(HpContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int insertSelective(HpContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	List<HpContent> selectByExampleWithBLOBs(HpContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	List<HpContent> selectByExample(HpContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	HpContent selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpContent record, @Param("example") HpContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") HpContent record, @Param("example") HpContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpContent record, @Param("example") HpContentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(HpContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_content
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpContent record);
}