package com.hpetshop.mapper;

import com.hpetshop.pojo.HpItemCat;
import com.hpetshop.pojo.HpItemCatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpItemCatMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	int countByExample(HpItemCatExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	int deleteByExample(HpItemCatExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	int insert(HpItemCat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	int insertSelective(HpItemCat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	List<HpItemCat> selectByExample(HpItemCatExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	HpItemCat selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpItemCat record, @Param("example") HpItemCatExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpItemCat record, @Param("example") HpItemCatExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpItemCat record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_cat
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpItemCat record);
}