package com.hpetshop.mapper;

import com.hpetshop.pojo.HpItemParamItem;
import com.hpetshop.pojo.HpItemParamItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpItemParamItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int countByExample(HpItemParamItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int deleteByExample(HpItemParamItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int insert(HpItemParamItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int insertSelective(HpItemParamItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	List<HpItemParamItem> selectByExampleWithBLOBs(HpItemParamItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	List<HpItemParamItem> selectByExample(HpItemParamItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	HpItemParamItem selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpItemParamItem record, @Param("example") HpItemParamItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") HpItemParamItem record, @Param("example") HpItemParamItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpItemParamItem record, @Param("example") HpItemParamItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpItemParamItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(HpItemParamItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param_item
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpItemParamItem record);
}