package com.hpetshop.mapper;

import com.hpetshop.pojo.HpItemDesc;
import com.hpetshop.pojo.HpItemDescExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpItemDescMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int countByExample(HpItemDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int deleteByExample(HpItemDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long itemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int insert(HpItemDesc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int insertSelective(HpItemDesc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	List<HpItemDesc> selectByExampleWithBLOBs(HpItemDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	List<HpItemDesc> selectByExample(HpItemDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	HpItemDesc selectByPrimaryKey(Long itemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpItemDesc record, @Param("example") HpItemDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") HpItemDesc record, @Param("example") HpItemDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpItemDesc record, @Param("example") HpItemDescExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpItemDesc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(HpItemDesc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_desc
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpItemDesc record);
}