package com.hpetshop.mapper;

import com.hpetshop.pojo.HpItemParam;
import com.hpetshop.pojo.HpItemParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpItemParamMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int countByExample(HpItemParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int deleteByExample(HpItemParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int insert(HpItemParam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int insertSelective(HpItemParam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	List<HpItemParam> selectByExampleWithBLOBs(HpItemParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	List<HpItemParam> selectByExample(HpItemParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	HpItemParam selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpItemParam record, @Param("example") HpItemParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") HpItemParam record, @Param("example") HpItemParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpItemParam record, @Param("example") HpItemParamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpItemParam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(HpItemParam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item_param
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpItemParam record);
}