package com.hpetshop.mapper;

import com.hpetshop.pojo.HpItem;
import com.hpetshop.pojo.HpItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	int countByExample(HpItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	int deleteByExample(HpItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	int insert(HpItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	int insertSelective(HpItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	List<HpItem> selectByExample(HpItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	HpItem selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpItem record, @Param("example") HpItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpItem record, @Param("example") HpItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_item
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpItem record);
}