package com.hpetshop.mapper;

import com.hpetshop.pojo.HpOrderItem;
import com.hpetshop.pojo.HpOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOrderItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	int countByExample(HpOrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	int deleteByExample(HpOrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	int insert(HpOrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	int insertSelective(HpOrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	List<HpOrderItem> selectByExample(HpOrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	HpOrderItem selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpOrderItem record, @Param("example") HpOrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpOrderItem record, @Param("example") HpOrderItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpOrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_item
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpOrderItem record);
}