package com.hpetshop.mapper;

import com.hpetshop.pojo.HpOrder;
import com.hpetshop.pojo.HpOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	int countByExample(HpOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	int deleteByExample(HpOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	int insert(HpOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	int insertSelective(HpOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	List<HpOrder> selectByExample(HpOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	HpOrder selectByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpOrder record, @Param("example") HpOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpOrder record, @Param("example") HpOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpOrder record);
}