package com.hpetshop.mapper;

import com.hpetshop.pojo.HpOrderShipping;
import com.hpetshop.pojo.HpOrderShippingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOrderShippingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	int countByExample(HpOrderShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	int deleteByExample(HpOrderShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	int insert(HpOrderShipping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	int insertSelective(HpOrderShipping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	List<HpOrderShipping> selectByExample(HpOrderShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	HpOrderShipping selectByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpOrderShipping record, @Param("example") HpOrderShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpOrderShipping record, @Param("example") HpOrderShippingExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpOrderShipping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_order_shipping
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpOrderShipping record);
}