package com.hpetshop.mapper;

import com.hpetshop.pojo.HpUser;
import com.hpetshop.pojo.HpUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	int countByExample(HpUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	int deleteByExample(HpUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	int insert(HpUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	int insertSelective(HpUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	List<HpUser> selectByExample(HpUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	HpUser selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") HpUser record, @Param("example") HpUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") HpUser record, @Param("example") HpUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(HpUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hp_user
	 * @mbggenerated
	 */
	int updateByPrimaryKey(HpUser record);
}